name: Backend Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend-tests:
    name: Run backend tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload report coverage back
        uses: actions/upload-artifact@v4
        with:
          name: report-coverage-back
          path: target/site/jacoco/*

      - name: Download report coverage back
        uses: actions/download-artifact@v4
        with:
          name: report-coverage-back