name: Docker Image Front

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image front
      run: docker build . --file Dockerfile --tag bobapp-front:$(date +%s)
