name: Frontend Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install
      working-directory: front

    - name: Build Angular Application
      run: npm run build
      working-directory: front

    - name: Run Tests with Coverage
      run: npm test -- --watch=false --browsers=ChromeHeadless --code-coverage
      working-directory: front      

    - name: Upload report coverage front
      uses: actions/upload-artifact@v4
      with:
        name: report-coverage-front
        path: front/coverage/bobapp/*

    - name: Download report coverage front
      uses: actions/download-artifact@v4
      with:
        name: report-coverage-front
      
