name: Frontend Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install
      working-directory: front

    - name: Build Angular Application
      run: npm run build
      working-directory: front

    - name: Run Tests with Coverage
      run: npm test -- --watch=false --browsers=ChromeHeadless --code-coverage
      working-directory: front      

    - name: Upload report coverage front
      uses: actions/upload-artifact@v4
      with:
        name: report-coverage-front
        path: front/coverage/bobapp

    - name: Pull latest changes
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git pull origin main 

    - name: Commit Karma report
      run: |
        git add front/coverage/bobapp
        git commit -m "Add Karma report"

    - name: Push Karma report
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

    - name: Download report coverage front
      uses: actions/download-artifact@v4
      with:
        name: report-coverage-front

    
  sonarcloud:
      runs-on: ubuntu-latest
      needs: test
      
      steps:
      - name: Checkout repository
        uses: actions/checkout@v4
          
      - name: Build and analyze Front end
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONT }}
        with:
          projectBaseDir: ./front
      
