name: Frontend Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install
      working-directory: front

    - name: Build Angular Application
      run: npm run build
      working-directory: front

    - name: Run Tests with Coverage
      run: npm run test --code-coverage
      working-directory: front

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: oc-10/front/coverage
