name: SonarCloud Front
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    
jobs:
  sonarcloud:
      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Build and analyze Front end
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ./front/

