name: SonarCloud
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    
jobs:
  sonarcloud:
      runs-on: ubuntu-latest
      
      steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      
      - name: Build and analyze Frontend code
        run: |
          cd front
          npm install
          npm run build
          sonar-scanner -Dsonar.projectKey=front -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=dversabeau -Dsonar.login=$SONAR_TOKEN
  
      - name: Build and analyze Backend code
        run: |
          cd back
          mvn clean verify sonar:sonar -Dsonar.projectKey=back -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=dversabeau -Dsonar.login=$SONAR_TOKEN
